##########################################################
## COLOR CUSTOMIZATIONS
## USE RBG FORMAT
##########################################################

[palette]
red = [248, 81, 73]
black = [13, 17, 23]
blue = [56, 139, 253]
white = [201, 209, 217]
gray = [110, 118, 129]
green = [63, 185, 80]
yellow = [202, 171, 0]

[priority]
emerg = [211, 10, 39]
alert = [198, 19, 22]
err = [206, 70, 6]
warn = [235, 82, 5]
notice = [255, 251, 0]
info = [35, 217, 35]
debug = [0, 122, 255]
unknown = [255, 255, 255]

[options]
# include services' description fields
description = true
# yank only the message/info or yank everything - info | full
yank = "info"
# initial priority is presented first when selecting a service - [1 - 7]
initial_priority = 5
# debug level - trace | debug | info | warn | error
debug_level = "info"
# are you using sudo in your system - sudo
command_format = "sudo"
# cursors
cursor_left = "▶"
cursor_right = "◀"
