[palette]
  red = [255, 0, 0]
  black = [0, 0, 0]
  blue = [0, 0, 255]
  white = [255, 255, 255]
  gray = [128, 128, 128]

[priority]
  emerg = [211, 10, 39]
  alert = [198, 19, 22]
  err = [206, 70, 6]
  warn = [235, 82, 5]
  notice = [255, 255, 0]
  info = [0, 255, 0]
  debug = [0, 0, 255]
  unknown = [255, 255, 255]

[debug_level]
  level = "info"
