[palette]
  red = [255, 0, 0]
  black = [0, 0, 0]
  blue = [0, 0, 255]
  white = [255, 255, 255]
  gray = [128, 128, 128]

[priority]
  emerg = [211, 10, 39]
  alert = [198, 19, 22]
  err = [206, 70, 6]
  warn = [235, 82, 5]
  notice = [255, 251, 0]
  info = [35, 217, 35]
  debug = [0, 122, 255]
  unknown = [255, 255, 255]

[debug_level]
  level = "info"

[options]
  # include services' description field
  description = true
  # yank only the message/info or yank everything - info | full
  yank = "info"
