name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Rust toolchain
    - name: Set up Rust
      uses: actions/toolchain@v1
      with:
        rust-version: stable

    # Formatting Check
    - name: Check formatting
      run: cargo fmt --all -- --check

    # Clippy Linting
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings

    # Build
    - name: Build
      run: cargo build --verbose

    # Tests
    - name: Run tests
      run: cargo test --verbose
